CPP      = i686-w64-mingw32-g++
CC       = i686-w64-mingw32-gcc
WINDRES  = i686-w64-mingw32-windres
RES      = WinMenu_private.res
OBJ      = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS     = -lmingw32 -lgcc -mwindows -static-libgcc
INCS     = 
CXXINCS  = 
BIN      = PHCK7Tool.exe
CXXFLAGS = $(CXXINCS)  -DWINDOWS
CFLAGS   = $(INCS)
RM       = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

WinMenu_private.res: WinMenu_private.rc rsrc.rc
	$(WINDRES) -i WinMenu_private.rc --input-format=rc -o WinMenu_private.res -O coff 

